# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-31 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixel.Category'),
            preserve_default=False,
        ),
    ]
